# Filename of GitKraken redistributable package
gitkraken_redis_filename: gitkraken-amd64.deb

# Path to GitKraken etag file
gitkraken_etag_path: '{{ gitkraken_download_dir }}/{{ gitkraken_redis_filename }}.etag'

# Default value for existing etag
gitkraken_existing_etag: none
