---
- hosts: '{{ target }}'
  become: True
  roles:
      - { role: angstwad.docker_ubuntu, pip_version_docker_py: 1.7.0 }
      - { role: gantsign.gitkraken }
      - { role: install } # Download this repo
      - { role: updateandrun, tags: [ updateandrun ] } # build docker and start this and dependend dockers
