---
- hosts: '{{ target }}'
  become: True
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
      - { role: gatherfacts }
      - { role: angstwad.docker_ubuntu }
      - { role: gantsign.gitkraken }
      - { role: install, tags: [ install, application ] } # Download this repo
      - { role: updateandrunbackend, tags: [ updateandrunbackend, application ] } # build docker and start this and dependend dockers
      - { role: updateandrunfrontend, tags: [ updateandrunfrontend, application ] } # build docker and start it
