---
- hosts: '{{ target }}'
  become: True
  roles:
      - angstwad.docker_ubuntu
      - gantsign.gitkraken
      - install # Download this repo
      - updateandrun # build docker and start this and dependend dockers
