---
- name: Checkout code
  git: repo={{ gitUrl }} dest={{ root }} force=yes accept_hostkey=True version={{ gitVersion }}

- name: Build docker
  become: True
  docker_image:
    path: "{{ root }}"
    state: present
    name: vuza/eventservice-backend

- name: Start database service
  become: True
  docker:
    name: eventService-redis
    image: redis
    state: started

- name: Start eventService-backend
  become: True
  docker:
    image: vuza/eventservice-backend
    state: reloaded
    ports:
      - "8080:8080"
    links:
      - "eventService-redis:redis"
