---
- name: Checkout code
  git: repo={{ gitUrl }} dest={{ root }} force=yes accept_hostkey=True version={{ gitVersion }}

- name: Build docker
  become: True
  docker_image:
    path: "{{ root }}"
    name: vuza/eventservice-backend
    force: True

- name: Start database service
  become: True
  docker_container:
    name: redis
    image: redis
    state: started

- name: Start eventService-backend
  become: True
  docker_container:
    name: vuza_eventservice-backend
    image: vuza/eventservice-backend
    ports:
      - "8080:8080"
    links:
      - "redis:redis"
